autumn/application/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^music/', include('music.urls', namespace='music')),
    url(r'^admin/', admin.site.urls),
]

autumn/music/urls.py
from music.views import track_list, album_detail, album_detail_data, track_add
from django.conf.urls import url

urlpatterns = [
    url(r'^track/list/$', track_list, name='track_list'),
    url(r'^track/add/$', track_add, name='track_add'),
    url(
        r'^album/(?P<album_id>\d+)/$',
        album_detail, name='album_detail'
    ),
    url(
        r'^album/(?P<album_id>\d+)/data/$',
        album_detail_data, name='album_detail_data'
    ),
]

autumn/example/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models

# Create your models here.

autumn/music/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models

class Track(models.Model):
    title = models.CharField(verbose_name='Название', max_length=256)
    duration = models.IntegerField(verbose_name='Длительность')
    release_date = models.DateField(verbose_name='Дата выпуска')
    artists = models.ManyToManyField(to='Artist', verbose_name='Исполнители')
    album = models.ForeignKey(to='Album', verbose_name='Альбом', null=True, blank=True)
    
    def __str__(self):
        return self.title
    
    class Meta:
        verbose_name = 'Композиция'
        verbose_name_plural = 'Композиции'


class Artist(models.Model):
    name = models.CharField(verbose_name='Имя', max_length=256)

    def __str__(self):
        return self.name
    
    class Meta:
        verbose_name = 'Исполнитель'
        verbose_name_plural = 'Исполнители'


class Album(models.Model):
    title = models.CharField(verbose_name='Название', max_length=256)
    artist = models.ForeignKey(to=Artist, verbose_name='Основной исполнитель')
    
    def __str__(self):
        return self.title

    class Meta:
        verbose_name = 'Альбом'
        verbose_name_plural = 'Альбомы'

autumn/music/forms.py
from django import forms
from music.models import Track


class TrackForm(forms.ModelForm):
    class Meta:
        model = Track
        fields = ('title', 'duration', 'release_date')

autumn/example/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.shortcuts import render

# Create your views here.

autumn/music/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse, JsonResponse
from music.models import Track, Album
from music.forms import TrackForm


def track_list(request):
    tracks = Track.objects.all()
    titles = ' '.join([track.title for track in tracks])
    return HttpResponse(titles)


def album_detail(request, album_id):
    album = get_object_or_404(Album, pk=album_id)
    tracks = Track.objects.filter(album=album)
    return render(request, 'album_detail.html', {'tracks': tracks, 'album': album })


def album_detail_data(request, album_id):
    album = get_object_or_404(Album, pk=album_id)
    tracks = Track.objects.filter(album=album)
    track_data = [{'id': t.id, 'title': t.title} for t in tracks]
    return JsonResponse({
        'tracks': track_data,
        'album': {'id': album.id, 'title': album.title},
    })


def track_add(request):
    if request.method == 'POST':
        form = TrackForm(request.POST)
        if form.is_valid():
            form.save()
            return JsonResponse({'status': 'ok'})
    else:
        form = TrackForm()
    
    return render(request, 'track_add.html', {'form': form})

autumn/music/templates/album_detail.html
{% extends "base.html" %}

{% block title %}
    Альбом {{ album.title }}
{% endblock %}

{% block content %}
    {% for track in tracks %}
        <div>
            <span class="track_title">{{ track.title }}</span> - <span class="track_duration">{{ track.duration }}</span>
        </div>
    {% endfor %}
{% endblock %}

autumn/music/templates/base.html
<html>
<head>
    <title>
        {% block title %}
        Сайт о музыке
        {% endblock %}
    </title>
    <link rel="stylesheet" href="/static/music.css"/>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.2/css/bootstrap.min.css" integrity="sha384-PsH8R72JQ3SOdhVi3uxftmaW6Vc51MKb0q5P2rRUpPvrszuE4W1povHYgTpBfshb" crossorigin="anonymous">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
</head>
<body class="container">
    <div class="row">
        <ul class="list-group col-sm-12 col-md-4">
            <li class="list-group-item">
                <a href="{% url 'music:track_list' %}">Все композиции</a>
            </li>
            <li class="list-group-item">
                <a href="{% url 'music:track_add' %}">Добавить трек</a>
            </li>
        </ul>
        <div class="content col-sm-12 col-md-8">
            {% block content %}{% endblock %}
        </div>
    </div>
</body>
</html>

autumn/music/templates/track_add.html
{% extends 'base.html' %}
{% block title %}
    Добавление трека
{% endblock %}

{% block content %}
    <form action="{% url 'music:track_add' %}" method="POST"> 
        {% csrf_token %}
        {{form.as_table}}
        <input type="submit"/>
    </form>
{% endblock %}